name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    uses: janosh/workflows/.github/workflows/pytest.yml@main
    with:
      python-version: "3.11"
    secrets: inherit
